### ISSUE TITLE
Screen support

### ISSUE THREAD

**Issue by hanhcode** [niikeec/virtual-grid#21]
Thanks for the great library. I think there will need to be an option to support different screens. For example, for desktop computers there will be 5 columns, for tablets there will be 3 columns, for mobile devices there will be 2 columns.

**Comment by niikeec** [comment]
Hey, you can currently do that by conditionally setting the columns amount. One way to know the current size is by using [media queries](https://github.com/shadcn-ui/ui/blob/03b1d783c4df6f2728a742efdebe7b014a6eb0fb/apps/www/hooks/use-media-query.tsx)

```
const sm = useMediaQuery("(min-width: 768px)");
const lg = useMediaQuery("(min-width: 1280px)");

const grid = useGrid({
    scrollRef,
    count: 10,
    columns: lg ? 3 : sm ? 2 : 1,
    ...
});
```
