### ISSUE TITLE
Responsive grids

### ISSUE THREAD

**Issue by sazzouz** [niikeec/virtual-grid#23]
Hi, thanks for this great package. What is considered the appropriate  way to implement responsive grid designs? I have experimented with dynamically changing the column number prop as the viewport changes size, but I'm not convinced in this approach. I would suspect this could be a common need and I'd like to know what the conventional wisdom is here? It doesn't appear feasible or correct to apply a grid wrapper with typical tailwind classes, for example, as the immediate child needs to be the grid items for virtualisation to work as intended.

Any help on achieving this would be greatly appreciated, I am attempting to extend the infinite scroll example with Tanstack Query, which is working, but I'm struggling with the markup. Thanks.

**Comment by niikeec** [comment]
Hey, the `columns` prop has an `auto` option ([example](https://github.com/niikeec/virtual-grid/blob/99925fecb6b8f67ca9bb9303ae76f8e3335dcc7b/examples/react/fixed/src/components/grid-auto/with-component.tsx#L11)). In case you want to control the number of columns then I would suggest [this approach](https://github.com/niikeec/virtual-grid/issues/21#issuecomment-2221485436).
